[package]
name = "rit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
flate2 = "1.0.26"
hex = "0.4.3"
hex-literal = "0.4.1"
sha1 = "0.10.5"
